# structurelint configuration
# Optimized for best practices and strict enforcement
# Documentation: https://github.com/structurelint/structurelint

root: true

exclude:
  - testdata/**
  - .git/**
  - __pycache__/**
  - .pytest_cache/**
  - .mypy_cache/**
  - .ruff_cache/**
  - venv/**
  - .venv/**
  - node_modules/**
  - dist/**
  - build/**
  - legacy_archive/**
  - examples/**
  - htmlcov/**
  - models/**
  - "*.egg-info/**"
  - copy_admin_password.bat  # Legitimate utility script
  - launch.bat  # Legitimate utility script

rules:
  # Phase 0: Basic filesystem structure
  # Strict limits based on actual project structure (max depth: 2, max files: 8)
  max-depth:
    max: 5  # Currently 2, allows growth but prevents deep nesting

  max-files-in-dir:
    max: 20  # Currently 8 max, allows growth while maintaining focus

  max-subdirs:
    max: 10  # Prevents excessive directory sprawl

  # Naming conventions - enforce Python snake_case strictly
  naming-convention:
    "**/*.py": "snake_case"
    "**/*.md": "UPPERCASE"  # UPPERCASE for documentation (README, ARCHITECTURE, etc.)
    "**/*.yml": "kebab-case"
    "**/*.yaml": "kebab-case"

  # File existence rules - security focused (no required files in subdirs)
  file-existence:
    # Security: No secrets or credentials anywhere
    ".env": "exists:0"
    "*.env": "exists:0"
    ".env.*": "exists:0"
    "*.secret": "exists:0"
    "*.secrets": "exists:0"
    "**/credentials.json": "exists:0"
    "**/secrets.yaml": "exists:0"
    "**/secrets.yml": "exists:0"
    "**/*.pem": "exists:0"
    "**/*.key": "exists:0"

  # Disallowed patterns - prevent clutter and security risks
  disallowed-patterns:
    # Temporary files
    - "*.tmp"
    - "*.temp"
    - "*~"

    # Backup files
    - "*.bak"
    - "*.backup"
    - "*.old"

    # Editor files
    - ".DS_Store"
    - "Thumbs.db"
    - "*.swp"
    - "*.swo"
    - "*~"
    - ".*.sw?"

    # IDE files (should be in .gitignore)
    - ".idea"
    - ".vscode/settings.json"  # Allow .vscode but not committed settings

    # Security
    - "*.pem"
    - "*.key"
    - "*secret*"
    - "*credential*"
    - "*.env*"

  # Regex pattern matching removed - structurelint implementation has issues with this feature

  # Test file validation - enforce comprehensive testing
  test-adjacency:
    pattern: "separate"
    test-dir: "tests/unit"
    file-patterns:
      - "**/*.py"
    exemptions:
      - "**/__init__.py"    # Package initializers
      - "**/conftest.py"    # Pytest configuration
      - "setup.py"          # Setup script
      - "run.py"            # Entry point script
      - "test_dictation.py" # Root-level test file (should eventually move)
      - "**/test_*.py"      # Test files themselves
      # Removed src/commands/base.py - it SHOULD have tests!

  test-location:
    integration-test-dir: "tests/integration"
    allow-adjacent: false
    exemptions:
      - "testdata/**"
      - "tests/**"
      - "test_*.py"  # Temporary: root-level test files (migrate to tests/)

# Phase 1: Architectural layers - strict dependency enforcement
layers:
  - name: "ui"
    description: "User interface layer - overlays and UI components"
    paths:
      - "src/overlays/**"
      - "src/ui/**"
    can-import:
      - "commands"
      - "core"

  - name: "commands"
    description: "Command processing and execution layer"
    paths:
      - "src/commands/**"
    can-import:
      - "core"
      - "audio"
      - "transcription"

  - name: "audio"
    description: "Audio processing and VAD"
    paths:
      - "src/audio/**"
    can-import:
      - "core"

  - name: "transcription"
    description: "Text processing and transcription"
    paths:
      - "src/transcription/**"
    can-import:
      - "core"

  - name: "core"
    description: "Core infrastructure - config, events, etc. (zero dependencies)"
    paths:
      - "src/core/**"
    can-import: []  # Core should have NO dependencies on other layers

# Phase 2: Dead code detection
entrypoints:
  - "src/main.py"
  - "run.py"
  - "setup.py"
  - "tests/**/test_*.py"
  - "test_*.py"

# Phase 4: File content templates (documentation standards)
file-templates:
  "**/*.py":
    required-sections:
      - pattern: '^""".*"""'  # Require module docstring
        description: "Python files must have module docstring"

  "src/**/README.md":
    required-sections:
      - pattern: "^#"  # Require heading
        description: "README files must have at least one heading"
